#pragma config(StandardModel, "RVW Fantasticbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Moving Forward
This program instructs your robot to move forward at full power for three seconds.
There is a two second pause at the beginning of the program.

Robot Model(s): Squarebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          VEX Motor             Right side motor
Motor Port 3        leftMotor           VEX Motor             Left side motor

*To run this sample program on Swervebot, be sure to Reverse Motor Port 3 in the Motors and Sensors
 Setup, and to make sure that Motor Port 2 is NOT Reversed.
----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at full power for 3 seconds
	motor[frontRightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[frontLeftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward
	motor[rearRightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[rearLeftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward

	wait1Msec(1800);			        // Robot runs previous code for 3000 milliseconds before moving on
//stop
	motor[frontRightMotor] = 0;		  // Motor on port2 is run at full (127) power forward
	motor[frontLeftMotor]  = 0;		  // Motor on port3 is run at full (127) power forward
	motor[rearRightMotor] = 0;		  // Motor on port2 is run at full (127) power forward
	motor[rearLeftMotor]  = 0;		  // Motor on port3 is run at full (127) power forward
	wait10Msec(1);

	// turn right
	motor[frontLeftMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[rearRightMotor] = -127;		  // Motor on port2 is run at full (127) power forward


	wait1Msec(3000);			        // Robot runs previous code for 3000 milliseconds before moving on

		// Move forward at full power for 3 seconds
	motor[frontRightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[frontLeftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward
	motor[rearRightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[rearLeftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward
	wait1Msec(2500);			        // Robot runs previous code for 3000 milliseconds before moving on

	}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
